[options]
admin_passwd = $pbkdf2-sha512$600000$TInxPgcghFAqBUCIESJk7A$lU1/DstHpW3XyB9dlsdcb25nSRw95f9qtpYiSTmhpppjyl.nJ7BWzSFwGF2CyqvQNrc9po1TeE5L0Lp0kPERuQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /opt/odoo/addons,/opt/odoo/odoo/addons,/opt/odoo/custom_addons
http_port = 8069
max_cron_threads = 1
limit_memory_hard = 3000000000
limit_memory_soft = 2800000000
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
log_level = info
db_maxconn = 64
list_db = True
server_wide_modules = base,web
proxy_mode = True

dbfilter = qwerty
db_name = qwerty
