[options]
admin_passwd = $pbkdf2-sha512$600000$jDGGcM4ZQ.h9b41RynkvJQ$Ypp5oPSH0Hk5QwSlMKcL66GgvKGZvVNVHczZlv292/U7GLx4bDozI36/FgvPEV5PMlbajNKOtrU736s3CrpMuA
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = c:\Users\Shashank patel\Desktop\client codes\FiberaFRP\FibraFRP-client-repo\odoo-19.0\odoo\addons,c:\Users\Shashank patel\Desktop\client codes\FiberaFRP\FibraFRP-client-repo\odoo-19.0\addons,c:\Users\Shashank patel\Desktop\client codes\FiberaFRP\FibraFRP-client-repo\odoo-19.0\custom_addons
http_port = 8069
log_level = info
list_db = True

