# -*- coding: utf-8 -*-
{
    'name': "ELSX WhatsApp Business",
    'summary': "WhatsApp Business Console with API, CRM, Campaigns, Automation, and AI Drafts",
    'version': '19.0.3.0.3',
    'category': 'Marketing/WhatsApp',
    'author': "ELSX Global",
    'license': 'LGPL-3',
    'depends': ['base', 'crm', 'contacts', 'mail', 'sale', 'account', 'base_setup'],
    'data': [
        'security/whatsapp_security.xml',
        'security/ir.model.access.csv',
        'data/elsx_ai_defaults.xml',
        'data/whatsapp_placeholder_data.xml',
        'data/whatsapp_cron.xml',
        'data/whatsapp_templates.xml',
        'views/whatsapp_message_views.xml',
        'views/whatsapp_template_views.xml',
        'views/whatsapp_bot_views.xml',
        'views/whatsapp_webhook_log_views.xml',
        'views/whatsapp_api_log_views.xml',
        'wizard/send_whatsapp_wizard_views.xml',
        'wizard/whatsapp_import_wizard_views.xml',
        'wizard/whatsapp_new_chat_wizard_views.xml',
        'wizard/whatsapp_invoice_send_wizard_views.xml',
        'views/whatsapp_scheduling_views.xml',
        'views/whatsapp_campaign_views.xml',
        'views/whatsapp_contact_views.xml',
        'views/whatsapp_account_views.xml',
        'views/whatsapp_chat_views.xml',
        'views/whatsapp_contact_segment_views.xml',
        'views/whatsapp_analytics_views.xml',
        'views/whatsapp_media_library_views.xml',
        'views/whatsapp_bot_flow_views.xml',
        'views/whatsapp_compliance_views.xml',
        'views/whatsapp_sample_template_views.xml',
        'views/whatsapp_quick_reply_views.xml',
        'views/whatsapp_placeholder_views.xml',
        'views/whatsapp_form_views.xml',
        'views/whatsapp_dashboard_views.xml',
        'views/elsx_ai_service_views.xml',
        'views/whatsapp_diagnostics_views.xml',
        'views/res_config_settings_views.xml',
        'views/account_move_views.xml',
        'views/whatsapp_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'elsx_whatsapp_marketing/static/src/css/whatsapp.css',
            'elsx_whatsapp_marketing/static/src/css/whatsapp_bot_flow_builder.css',
            'elsx_whatsapp_marketing/static/src/js/notification_tones.js',
            'elsx_whatsapp_marketing/static/src/js/elsx_ui_motion.js',
            'elsx_whatsapp_marketing/static/src/js/whatsapp_widget.js',
            'elsx_whatsapp_marketing/static/src/js/whatsapp_bot_flow_builder.js',
            'elsx_whatsapp_marketing/static/src/js/whatsapp_bot_flow.js',
            'elsx_whatsapp_marketing/static/src/js/whatsapp_dashboard.js',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
}
