from . import account_move
from . import crm_lead
from . import res_config_settings
from . import res_partner
from . import runtime
from . import sale_order
from . import ui_preferences
from . import uninstall_readiness
from . import whatsapp_account
from . import whatsapp_analytics
from . import whatsapp_api_log
from . import whatsapp_bot
from . import whatsapp_bot_flow
from . import whatsapp_campaign
from . import whatsapp_campaign_participant
from . import whatsapp_campaign_step
from . import whatsapp_chat
from . import whatsapp_chat_note
from . import whatsapp_compliance
from . import whatsapp_contact
from . import whatsapp_contact_segment
from . import whatsapp_diagnostics
from . import whatsapp_form
from . import whatsapp_media_library
from . import whatsapp_message
from . import whatsapp_placeholder
from . import whatsapp_quick_reply
from . import whatsapp_sample_template
from . import whatsapp_scheduling
from . import whatsapp_template
from . import whatsapp_webhook_log
