from . import whatsapp_account
from . import whatsapp_message
from . import whatsapp_campaign
from . import whatsapp_campaign_step
from . import whatsapp_template
from . import whatsapp_contact
from . import res_partner
from . import sale_order
from . import account_move
from . import crm_lead
